# fly.toml file generated for trellix on 2023-11-03T17:18:04-06:00

app = "trellix"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[experimental]
allowed_public_ports = []
auto_rollback = true
cmd = "start.sh"
entrypoint = "sh"

[mounts]
destination = "/data"
source = "myapp_data"

[[services]]
internal_port = 8080
processes = ["app"]
protocol = "tcp"

[services.concurrency]
hard_limit = 25
soft_limit = 20
type = "connections"

[[services.ports]]
force_https = true
handlers = ["http"]
port = 80

[[services.ports]]
handlers = ["tls", "http"]
port = 443
